
CC=gcc # -Wall


all: lbfgsb.o ancestry-gll.c lbfgsb.h lbfgsb.c
	$(CC) lbfgsb.o -lm -o ANCESTRY ancestry-gll.c 


lbfgsb.o: lbfgsb.h lbfgsb.c
        $(CC) -o lbfgsb.o -c lbfgsb.c


clean:
	rm -f lbfgsb.o ANCESTRY
